subject = "Теория графов"
description = "Материалы для подготовки к зачёту"
term = 5 # номер семестра
authors = [
  "Егор Смирнов",
  "Артём Рудяк",
  "Артём Соловьёв",
  "Александр Храмов",
  "Роберт Толстов",
  "Данила Григорьев",
  "Михаил Чертков",
  "Виктория Лазарева",
  "Вадим Карасев",
  "Артём Кудяков",
  "Радомир Тюменцев",
  "Александр Железко",
  "Иван Архипов",
  "Михаил Леонтьев",
  "Маргарита Потапкина"
]

[sections]
numbering = true
prefix = "Вопрос"
sections = [
  "История возникновения и развития теории графов. Задача о кенигсбергских мостах, головоломка Гамильтона, задача о четырех красках, задачи связанные с химией и физикой.",
  "Прикладные задачи теории графов. Веб-граф, графы социальных сетей, кластеризация и др. задачи. Графы де Брейна и биоинформатика. Деревья решений. Графы дорог. Графы и автоматы.",
  "Понятие графа, основные определения (вершины, ребра, дуги, ориентированные и неориентированные графы, простой граф, мультиграф, петли, кратные ребра). Виды графов: полный, двудольный, полный двудольный. Дополнение. Изоморфизм. Примеры.",
  "Степени вершин, теорема Эйлера. Примеры (количество ребер в полном и полном двудольном графах). ",
  "Маршруты, пути, цепи, циклы. Связность, компоненты связности. Расстояние, диаметр, эксцентриситет, центр. Примеры",
  "Теорема Кенига. Примеры",
  "Понятие связности для орграфов. Граф компонент сильной связности. Турнир.",
  "Подграф. Операции удаления вершин и ребер. Остовной подграф. Точки сочленения и мосты, их свойства.",
  "Понятие дерева. Свойства деревьев. ",
  "Помеченные деревья. Теорема Кэли.",
  "Эйлеров путь, эйлеров цикл. Определение, критерии существования эйлерова пути, эйлерова цикла. Примеры. Прикладные задачи. Аналоги для ориентированных графов.",
  "Гамильтонов путь, гамильтонов цикл. Определения, примеры, теорема Оре, следствие (теорема Дирака). Примеры. Понятие замыкание. Теоремы Хватала и Бонди-Хватала. Результаты для некоторых классов графов (например: полный, двудольный). Прикладные задачи. Аналоги для ориентированных графов.",
  "Планарные графы. Грань, степень грани, аналог теоремы Эйлера. Теорема (формула Эйлера), следствия. Теорема Куратовского (критерий Понтрягина-Куратовского). Примеры. ",
  "Вершинная раскраска графа. Хроматическое число. Основные результаты. Теорема Брукса. Нижняя оценка. Теорема Мицельского.",
  "Представление графов: матрица смежности, матрица инциденций, списки смежности. Преимущества и недостатки. Примеры.",
  "Поиск кратчайших путей во взвешенном графе. Основные понятия. Постановка задачи. Алгоритм Дейкстры, алгоритм Флойда, алгоритм Форда-Беллмана. Примеры. ",
  "Обходы графов: в ширину и глубину (рекурсивная и нерекурсивная реализация). Алгоритмы, основанные на алгоритмах обхода: нахождение компонент связности, поиск кратчайших путей, топологическая сортировка, проверка на ацикличность, проверка на двудольность, построение стягивающего дерева. Примеры.",
  "Потоки. Величина потока, разрез графа, алгоритм Форда-Фалкерсона.",
]

